language: php
php:
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - php: 7.0
before_install:
  - wget https://deb.nodesource.com/setup_4.x -qO- | sudo bash
  - sudo apt-get install -y nodejs graphviz
  - echo "$(which php) /usr/local/php" | sudo xargs ln -s
  - "printf '\n' | pecl install -f 'mailparse-'$(php -r \"echo (-1 === version_compare(phpversion(), '7.0.0') ? '2.1.6' : '3.0.2');\")"
install:
  - sudo npm install -g --unsafe-perm .
  - sudo rm -rf ~/.composer/cache
script:
  - ./tests/bootstrap
