language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_install:
  - curl -sL https://deb.nodesource.com/setup | sudo bash -
  - sudo apt-get install -y nodejs
install:
  - sudo npm install -g --unsafe-perm .
  - rm -rf ~/.composer/cache
script:
  - ./tests/bootstrap
